"""remove_qr_code_url_from_users

Revision ID: 08a630e4937a
Revises: 3cabf04e6af2
Create Date: 2026-05-14 01:40:28.832624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08a630e4937a'
down_revision = '3cabf04e6af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_members_event_id_fkey'), 'event_members', type_='foreignkey')
    op.drop_constraint(op.f('event_members_user_id_fkey'), 'event_members', type_='foreignkey')
    op.create_foreign_key(None, 'event_members', 'events', ['event_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'event_members', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.drop_column('users', 'qr_code_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('qr_code_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'event_members', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('event_members_user_id_fkey'), 'event_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('event_members_event_id_fkey'), 'event_members', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
