"""add_user_fcm_tokens_table

Revision ID: 25679552766d
Revises: 08a630e4937a
Create Date: 2026-05-14 02:59:55.428507

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '25679552766d'
down_revision = '08a630e4937a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fcm_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fcm_tokens_fcm_token'), 'user_fcm_tokens', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_user_fcm_tokens_user_id'), 'user_fcm_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('event_members_user_id_fkey'), 'event_members', type_='foreignkey')
    op.drop_constraint(op.f('event_members_event_id_fkey'), 'event_members', type_='foreignkey')
    op.create_foreign_key(None, 'event_members', 'events', ['event_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'event_members', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'event_members', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('event_members_event_id_fkey'), 'event_members', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('event_members_user_id_fkey'), 'event_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_fcm_tokens_user_id'), table_name='user_fcm_tokens')
    op.drop_index(op.f('ix_user_fcm_tokens_fcm_token'), table_name='user_fcm_tokens')
    op.drop_table('user_fcm_tokens')
    # ### end Alembic commands ###
