"""add_bank_details_to_users

Revision ID: 3cabf04e6af2
Revises: 98e2cc94f7d3
Create Date: 2026-05-14 01:18:23.937461

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3cabf04e6af2'
down_revision = '98e2cc94f7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_members_event_id_fkey'), 'event_members', type_='foreignkey')
    op.drop_constraint(op.f('event_members_user_id_fkey'), 'event_members', type_='foreignkey')
    op.create_foreign_key(None, 'event_members', 'events', ['event_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'event_members', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.alter_column('notifications', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('users', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('users', sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('users', sa.Column('account_holder', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_holder')
    op.drop_column('users', 'account_number')
    op.drop_column('users', 'bank_name')
    op.alter_column('notifications', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'event_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'event_members', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('event_members_user_id_fkey'), 'event_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('event_members_event_id_fkey'), 'event_members', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
